apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: ambrosia-serve
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ambrosia-server
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
