apiVersion: v1
kind: Service
metadata:
  namespace: ambrosia-serve
  name: ambrosia-server
spec:
  selector:
    app: ambrosia-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

