apiVersion: v1
kind: Service
metadata:
  namespace: ambrosia-serve
  name: ambrosia-server
spec:
  selector:
    app: ambrosia-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
  