name: Terraform Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Initialize Terraform
      run: terraform init
  
    - name: Destroy Terraform Infrastructure      
      run: terraform destroy -auto-approve 
        -var="access_key=${{secrets.AWS_ACCESS_KEY_ID}}"
        -var="secret_key=${{secrets.AWS_SECRET_ACCESS_KEY}}"
        -var="token=${{secrets.AWS_SESSION_TOKEN}}"
